# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmNjN2U4MmRlNDA4MTFjNTVlZGI3MjFiNjlmOGE2ODQ2ZTZiMjI5ODI4YzM0NzE3Yzg3MDNlYTlhOTM4MjA3ZWVlNGY3MTg1ZTUyYjNkNmJiOTU1ZGY0Mjc1NWU0NWU0NzE3Y2NkOTA5OWQzYmYxYmM3OWVkYmVjNTIzMjVhYWE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
